### ISSUE TITLE
Beispiel mit Transaktionsdaten 

### ISSUE THREAD

**Issue by ddv1212** [bwurst/python-tse#1]
Hey, 

Kannst du vielleicht ein Beispiel hochladen indem ersichtlich wird wie du Transaktionsdaten übergibst?

Darfst du Angaben zum Preis vom dev modul machen?

Lg

**Comment by bwurst** [comment]
Ich habe die Readme zum Thema processdata angepasst und eine Beispiel-Implementierung aus meinem Projekt als example in das Repo gestellt.

Die Transaktionsdaten sind sowohl der TSE als auch dem Modul egal und werden in der DSFinV-K festgelegt.
Einige Beispiel-Daten sind z.B. unter https://support.gastro-mis.de/support/solutions/articles/36000170276-processtype-und-processdata oder https://support.gastro-mis.de/support/solutions/articles/36000170993-use-cases-und-fallbeispiele-wie-muss-was-abgesichert-werden

Als Dev-Modul wurde das hier verwendet: https://tse.gastro-mis.de/tse/produkt/tse-implementierungspaket2/

**Comment by ddv1212** [comment]
Danke dafür!

Ich habe nun mein Dev Kit erhalten und frage mich nun wo ich die PINs und die PUK herbekommen. Außerdem ist mir aufgefallen, dass es diverse Libs für verschiedene Architekturen als auch Sprachen vorhanden sind. Die Architektur ist bei mir klar, allerdings nicht welche Sprache. Ich vermute hier C. Liege ich da  richtig? 

LG

**Comment by bwurst** [comment]
Als Library wird die C-Library verwendet, ja.
PIN und PUK werden bei der Inbetriebnahme festgelegt, steht unter "Einmaliges Initialisieren der TSE" in der README.
