### ISSUE TITLE
Problem mit TSE auf Raspberry Pi 3 B+

### ISSUE THREAD

**Issue by ddv1212** [bwurst/python-tse#2]
Hallo, muss mich leider nochmal mit einem Problem melden.

**Setup:**
Raspberry Pi 3 Model B Plus Rev 1.3
Raspbian GNU/Linux 10 (buster)
Python 3.7.3
ARM Library der TSE

Getestet habe ich mit /example/TSE.py

**Problem 1**
Output:
```
Traceback (most recent call last):
  File "example/TSE.py", line 2, in <module>
    conf['library'] = os.path.join(os.path.dirname(__file__), '../src/lib')
NameError: name 'conf' is not defined
```
Das Problem ist eher unwichtig. Habe die conf Parameter an den entsprechenden Stellen einfach direkt übergeben.

**Problem 2**
Output:
```
cannot find TSE unit on any mount path
TSE: Exception occured whilst initializing TSE. Possibly no module present?!
Traceback (most recent call last):
  File "example/TSE.py", line 90, in <module>
    print('Signaturzähler: %s' % tse.info.createdSignatures)
AttributeError: 'NoneType' object has no attribute 'createdSignatures'
```

Anschließend habe ich die TSE eingehängt und ein paar Ausgaben zum debuggen ergänzt.
Output:
```
self: <worm.Worm object at 0x766ba930>
mountpoint: /media/usb
ret worm init: 3
TSE: Exception occured whilst initializing TSE. Possibly no module present?!
Traceback (most recent call last):
  File "example/TSE.py", line 90, in <module>
    print('Signaturzähler: %s' % tse.info.createdSignatures)
AttributeError: 'NoneType' object has no attribute 'createdSignatures'
```
In Zeile 82 von worm.py fliegt dann die Exception auf Grund des folgenden Fehlercodes: 
> 3: WORM_ERROR_IO'

Hast du eine Idee warum es zu diesem IO Fehler kommt? Ist das eventuell ein Berechtigungsproblem?

LG

**Comment by bwurst** [comment]
Problem 1: Die TSE.py ist ein Beispiel, wie ich es bei mir in meinem Kassenprogramm eingebunden habe. Die ist nicht so lauffähig wie sie ist, ja. Zum einfachen Testen der Funktionen sollte die ./src/cli/test.py besser geeignet sein.

Problem 2:
Es tut mir leid, ich kann dazu keinen Support leisten. Ich habe das so programmiert, dass es bei mir getan hat und habe es so dokumentiert, dass man meine Vorgehensweise hoffentlich nachvollziehen kann. Wie es sich unter unterschiedlichen Distributionen auf unterschiedlichen Plattformen verhält, weiß ich schlicht und einfach nicht. Ich kann das auch nicht selbst testen, habe im Moment keine Entwickler-TSE mehr zur Hand.

Die TSE ist für die Software ein einfacher Massenspeicher. Nach dem Mounten sind da Dateien. Die werden gelesen und geschrieben. Von daher lassen sich die Berechtigungen ganz einfach nachschauen und prüfen. 
Mein Setup ist eine Distribution, die Speichermedien automatisch für den eingeloggten User mountet. Wenn du diese als root gemountet hast und als User zugreifst, ja, dann wird es wohl nicht funktionieren. Da fühle ich mich aber weder in der Lage noch in der Pflicht, tiefer in die Problemfindung einzusteigen.
