### ISSUE TITLE
Fragen zu Zeitaktualisierung und Login/Logout

### ISSUE THREAD

**Issue by utelle** [bwurst/python-tse#3]
Zunächst einmal vielen Dank, dass Du diese Komponente hier zur Verfügung stellst. Sehr hilfreich!

Ich hätte zur Implementierung 2 kleine Rückfragen:

1) Um regelmäßig die TSE-Zeit zu setzen startest Du in Deiner TSE-Beispielimplementierung einen separaten Thread, der in entsprechenden Zeitabständen die Funktion `tse_updateTime´ aufruft. In der Dokumentation der SwissBit-TSE heißt es allerdings, dass die Worm-Bibliothek nicht multithreading-fähig sei. Kann es da nicht zu Konflikten kommen, wenn im Main-Thread z.B. eine Transaktion stattfindet und der Worker-Thread mittendrin - oder gar gleichzeitig - eine Aktualisierung der Zeit durchführt?

2) Die Funktion zur Aktualisierung der TSE-Zeit ruft jedes Mal die Funktion `user_login` für den User `time_admin` auf, aber nie die Funktion `user_logout`. Ist das beabsichtigt? Wäre es nicht besser, jeweils nach Setzen der Zeit auch ein Logout durchzuführen?

**Comment by bwurst** [comment]
zu 1.: Im Prinzip ist die Klasse ja als Singleton ausgelegt und es gibt auch Locking, so dass nur ein Thread aktiv sein sollte. Aber ja, die reguläre Nutzung aus dem Programm heraus könnte hier parallel passieren und ist bisher nicht über ein locking abgesichert. Ich glaube, das Problem lässt sich lösen, wenn man die Zeile 115 (in `__getattr__`) noch über das Lock sichert. Also "`with self.__class__._lock:`" davor. Dann wird auch die reguläre Nutzung über das Lock gesperrt und die Anfragen sollten sich nicht mehr überschneiden. Ich habe das aber nicht getestet.

zu 2.: Ich habe bisher keine negativen Effekte des wiederkehrenden Aufrufs von user_login bemerkt aber im Prinzip ist das unnötig, ja. Entweder sollte man in der Library speichen ob man schon angemeldet ist oder erstmal ohne Login probieren und auf eine ensprechende Fehlersituation reagieren. Oder jedes Mal ausloggen. Ich weiß nicht, was der bevorzugte Weg ist.

**Comment by utelle** [comment]
Vielen Dank für die flotte Antwort.

zu 1: Ich werde Deinem Lösungsvorschlag folgen. Damit sollte man dann auf der sicheren Seite sein.

zu 2: Tja, darüber, was der bevorzugte Weg ist, schweigt sich die WormLib-Dokumentation - wie auch über manche anderen Aspekte - leider aus. Von einem kostenpflichtigen Entwickler-Kit hatte ich mir da wahrlich mehr versprochen ... aber das ist ein anderes Thema. "Sauberer" wäre es vermutlich, wenn man entweder nach jedem Zeit-Update ein Logout macht. Alternativ könnte man den Time-Admin einmalig zu Beginn anmelden.

Nochmals ein großes Danke! :smile:
