### ISSUE TITLE
Integration Epson USB-TSE?

### ISSUE THREAD

**Issue by strubbi77** [bwurst/python-tse#4]
Ich habe eine Epson USB-TSE, die Aufrufbibliothek für Epson sind komplett verschieden zu dem hier aus. Ist es geplant auch für die Epson USB-TSE eine Bibliothek zu erstellen oder ist das komplett out of scope?

Viele Grüße
Thomas Strub

**Comment by bwurst** [comment]
Für mich selbst ist das zum jetzigen Zeitpunkt komplett out of scope weil ich halt nun eine Swissbit-TSE habe und keinen Vorteil aus der Unterstützung weiterer TSEs erkennen kann.
Wenn jemand ausreichend Gemeinsamkeiten erkennt und ein einheitliches API zwischen verschiedenen Systemen implementieren möchte, finde ich das eine großartige Sache und werde gerne unterstützen und Patches annehmen. Vermutlich wird dafür aber dieser Code nicht die geeignete Basis sein, da ich wirklich nah an der Swissbit-API entlang programmiert habe.
