### ISSUE TITLE
ARM / Raspberry

### ISSUE THREAD

**Issue by andreasmueller1987** [bwurst/python-tse#5]
Moin,

kann es sein, dass die Swissbit TSE bzw. diese Software nicht mit dem Raspberry bzw. ARM Prozessor läuft?

Kann das jemand bestätigen?
Ich habe in alten Beiträgen gelesen, dass es noch nicht unterstützt wird.
Der Distributor der Swissbit TSE sagte, dass es mittlerweile unterstützt wird.

Viele Grüße

**Comment by bwurst** [comment]
Python sollte ja plattformunabhängig sein und die von mir verwendeten Sprachelemente sollten auch auf Raspberry funktionieren.

Ich selbst habe aber nicht das vollständige und aktuelle Entwickler-Kit von Swissbit und daher habe ich nicht die für ARM nötige binär-Library libWormAPI.so. Mein Kontakt, der mir diese zugänglich gemacht hat ist leider nicht mehr verfügbar. 

Wenn diese library vorliegt, sollte es eigentlich gehen. Ich kann es aber nicht testen.
